
spring:
    profiles:
        active: dev
    mvc:
        view:
            prefix: /templates/
            suffix: .html
    thymeleaf:
        cache: false
    redis:
        database: 0
        port: 6379
        host: 127.0.0.1
    datasource:
        url: jdbc:mysql://47.99.116.137:3306/tansu?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
        username: root
        password: swp123456
        driver-class-name: com.mysql.cj.jdbc.Driver
servlet:
    multipart:
      enabled: true
redis:
    config:
        password: 123456        
mybatis:
    mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
    type-aliases-package: com.swp.fileupload.model  # 注意：对应实体类的路径
server:
    port: 8080